<<<<<<< HEAD
cookie:
  expiry_days: 7
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      name: Admin
      password: $2b$12$ms7blfb8SbTei8P0eyTtFuTPdlmYDesZNICdieYBEYKCuROMEfg..
    louisvuitton:
      email: louisvuitton@gmail.com
      name: Louis Vuitton
      password: $2b$12$1luIzwq.E7hHBMFVSVtTy.R2df4QBsmaddD6u4emCEZxGOlzy4pQe
preauthorized:
  emails:
  - melsby@gmail.com
=======
cookie:
  expiry_days: 7
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      name: Admin
      password: $2b$12$ms7blfb8SbTei8P0eyTtFuTPdlmYDesZNICdieYBEYKCuROMEfg..
    louisvuitton:
      email: louisvuitton@gmail.com
      name: Louis Vuitton
      password: $2b$12$1luIzwq.E7hHBMFVSVtTy.R2df4QBsmaddD6u4emCEZxGOlzy4pQe
preauthorized:
  emails:
  - melsby@gmail.com
>>>>>>> 2af3e2017849036876ff7d81b7c5b62fb6ee306d
